version: '3.2'

services:
  flask:
    build: /home/ubuntu/P5_OpenClassroomsProject/Docker_api
    container_name: flask
    restart: always
    mem_limit: 2g
    environment:
      - APP_NAME=Moreno_Bastien_5_code_API_022024
    expose:
      - 8080
    ports:
      - "8080:8080"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"  # Expose le port 80 de Nginx sur le port 80 de la machine hôte
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask